/*
 * TSPframe.java
 *@author Ziang Jia
 *@Email ziangj92@gmail.com
 *@Date 06/01/2014
 */

package gadesign.TSPframes;

import gadesign.algoritms.InitialParameters;
import gadesign.algoritms.OverallBest;
import gadesign.algoritms.TSPAlgorithm;
import gadesign.entitys.DataCon;
import gadesign.entitys.Station;
import gadesign.entitys.Tool;
import gadesign.entitys.utils.Util;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import jxl.Sheet;
import jxl.Workbook;

import com.sun.org.apache.xerces.internal.util.URI;

/**
 * 
 * @author Jia Ziang
 * @see ziangj92@gmail.com
 * @since 06/01/2014
 * @version 1.0
 *
 */

public class TSPframe extends javax.swing.JFrame {

	DataCon dclocal = null;
	List<OverallBest> obList = new ArrayList<OverallBest>();

	/** Creates new form TSPframe */
	public TSPframe() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		doGA = new javax.swing.JButton();
		back = new javax.swing.JButton();
		checkParam = new javax.swing.JButton();
		inputExcel = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jLabel8 = new javax.swing.JLabel();
		APIkey = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		MapDataPath = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		setTool = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		setParam = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jSeparator4 = new javax.swing.JSeparator();
		jSeparator5 = new javax.swing.JSeparator();
		jSeparator6 = new javax.swing.JSeparator();
		jSeparator7 = new javax.swing.JSeparator();
		jSeparator8 = new javax.swing.JSeparator();
		inputFromInternet = new javax.swing.JButton();
		dataInputPath = new javax.swing.JTextField();
		ReadMap = new javax.swing.JButton();
		jSeparator9 = new javax.swing.JSeparator();
		jSeparator10 = new javax.swing.JSeparator();
		jLabel5 = new javax.swing.JLabel();
		jSeparator11 = new javax.swing.JSeparator();
		jLabel6 = new javax.swing.JLabel();
		resultPathText = new javax.swing.JTextField();
		ChooseResultPath = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		doGA.setText("\u751f\u6210\u6821\u8f66\u8def\u5f84");
		doGA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				doGAActionPerformed(evt);
			}
		});

		back.setText("\u8f93\u51fa");
		back.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backActionPerformed(evt);
			}
		});

		checkParam.setText("\u68c0\u67e5\u53c2\u6570");
		checkParam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkParamActionPerformed(evt);
			}
		});

		inputExcel.setText("\u5bfc\u5165\u6587\u4ef6");
		inputExcel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inputExcelActionPerformed(evt);
			}
		});

		jLabel1.setText("\u7ad9\u70b9\u5750\u6807\u6587\u4ef6");

		jLabel2
				.setText("\u6821\u8f66\u8def\u5f84\u4f18\u5316\u7b97\u6cd5\u5de5\u5177\u7bb1");

		jLabel8.setText("\u767e\u5ea6API\u5bc6\u94a5");

		APIkey.setText("w5ZUl1WCVWMOTOz6zSHqiCNy");

		jLabel9.setText("\u4f18\u5316\u53c2\u6570\u5de5\u5177\u680f");

		jLabel11.setText("\u6570\u636e\u5b58\u50a8\u8def\u5f84");

		jLabel12.setText("\u7f51\u7edc\u6570\u636e\u63a5\u53e3");

		setTool.setText("\u8bbe\u7f6e");
		setTool.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				setToolActionPerformed(evt);
			}
		});

		jLabel3.setText("\u7b97\u6cd5\u53c2\u6570\u5de5\u5177\u680f");

		setParam.setText("\u8bbe\u7f6e");
		setParam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				setParamActionPerformed(evt);
			}
		});

		jLabel4.setText("\u8def\u5f84\u4f18\u5316\u5de5\u5177");

		inputFromInternet.setText("\u9009\u62e9\u8def\u5f84");
		inputFromInternet
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						inputFromInternetActionPerformed(evt);
					}
				});

		ReadMap.setText("\u8bfb\u53d6\u6570\u636e");
		ReadMap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ReadMapActionPerformed(evt);
			}
		});

		jLabel5.setText("\u7ed8\u5236\u5730\u56fe\u63a5\u53e3");

		jLabel6.setText("\u7ed3\u679c\u5b58\u50a8\u8def\u5f84");

		ChooseResultPath.setText("\u9009\u62e9\u8def\u5f84");
		ChooseResultPath.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ChooseResultPathActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(399, 399,
										399).addComponent(jLabel2)
										.addContainerGap(625, Short.MAX_VALUE))
						.addGroup(
								layout.createSequentialGroup().addGap(77, 77,
										77).addComponent(jLabel5)
										.addContainerGap(1022, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				93,
																				93,
																				93)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				51,
																				51,
																				51)
																		.addComponent(
																				dataInputPath,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				459,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				93,
																				93,
																				93)
																		.addComponent(
																				inputExcel))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				53,
																				53,
																				53)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jSeparator7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								139,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jSeparator11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								139,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jSeparator9)
																						.addComponent(
																								jSeparator5)
																						.addComponent(
																								jSeparator3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								872,
																								Short.MAX_VALUE)
																						.addComponent(
																								jSeparator10)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				53,
																				53,
																				53)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jSeparator2,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								865,
																								Short.MAX_VALUE)
																						.addComponent(
																								jSeparator8,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jSeparator6,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jSeparator4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																139,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGroup(
																																layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																		.addComponent(
																																				jLabel6)
																																		.addComponent(
																																				jLabel9)))
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				131,
																																				131,
																																				131)
																																		.addComponent(
																																				jLabel3)
																																		.addGap(
																																				110,
																																				110,
																																				110)
																																		.addComponent(
																																				checkParam)
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				doGA)
																																		.addGap(
																																				42,
																																				42,
																																				42)
																																		.addComponent(
																																				back))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				48,
																																				48,
																																				48)
																																		.addComponent(
																																				resultPathText,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				461,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				ChooseResultPath)))
																										.addGap(
																												41,
																												41,
																												41)))))
										.addContainerGap())
						.addGroup(
								layout.createSequentialGroup().addGap(70, 70,
										70).addComponent(jLabel4)
										.addContainerGap(1029, Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				73,
																				73,
																				73)
																		.addComponent(
																				jLabel12)
																		.addGap(
																				75,
																				75,
																				75))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap(
																				91,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel11)
																		.addGap(
																				58,
																				58,
																				58)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addGap(
																				45,
																				45,
																				45)
																		.addComponent(
																				APIkey))
														.addComponent(
																MapDataPath,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																460,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(88, 88, 88)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(ReadMap)
														.addComponent(
																inputFromInternet))
										.addGap(309, 309, 309)).addGroup(
								layout.createSequentialGroup().addGap(105, 105,
										105).addComponent(setTool).addGap(178,
										178, 178).addComponent(setParam)
										.addContainerGap(780, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(45, 45, 45)
										.addComponent(jLabel2)
										.addGap(34, 34, 34)
										.addComponent(
												jSeparator6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												13,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																dataInputPath,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																inputExcel))
										.addGap(18, 18, 18)
										.addComponent(
												jSeparator8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												16,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel4)
										.addGap(18, 18, 18)
										.addComponent(
												jSeparator4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(jLabel3)
														.addComponent(
																checkParam)
														.addComponent(doGA)
														.addComponent(back))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(setParam)
														.addComponent(setTool))
										.addGap(19, 19, 19)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																resultPathText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																ChooseResultPath))
										.addGap(33, 33, 33)
										.addComponent(
												jSeparator5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												2,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12)
														.addComponent(jLabel8)
														.addComponent(
																inputFromInternet)
														.addComponent(
																APIkey,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(
												jSeparator7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel11)
														.addComponent(ReadMap)
														.addComponent(
																MapDataPath,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addComponent(
												jSeparator9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(1, 1, 1)
										.addComponent(
												jSeparator10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel5)
										.addGap(18, 18, 18)
										.addComponent(
												jSeparator11,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(264, 264, 264)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 
	 * @author Jia Ziang
	 * @see ziangj92@gmail.com
	 * @since 06/01/2014
	 * @version 1.0
	 *
	 */

	private void ChooseResultPathActionPerformed(java.awt.event.ActionEvent evt) {
		// 选择结果的存储路径
		final JFileChooser fc = new JFileChooser();
		fc.showOpenDialog(this);
		try {

			if (fc.showSaveDialog(this) == 0) {
				Tool.DATAOUTPUTPATH = fc.getSelectedFile().getPath();
				JOptionPane.showMessageDialog(this, "路径保存成功");

			} else {
				JOptionPane.showMessageDialog(this, "没有选择文件");
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "没有选择文件");
		} finally {
			this.resultPathText.setText(Tool.DATAOUTPUTPATH);
			System.out.println(Tool.DATAOUTPUTPATH);
		}

	}

	

	private void ReadMapActionPerformed(java.awt.event.ActionEvent evt) {
		// 读取地图数据
		try {
			this.dclocal = new DataCon(this.APIkey.getText(), Tool.MAPDATAPATH,
					Tool.DATAINPUTPATH);
			JOptionPane.showMessageDialog(this, "读取数据成功！");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "路径不能为空！");
		}
	}

	private void inputFromInternetActionPerformed(java.awt.event.ActionEvent evt) {
		// 选择地图数据存储路径
		final JFileChooser fc = new JFileChooser();
		fc.showOpenDialog(this);
		try {

			if (fc.showSaveDialog(this) == 0) {
				Tool.MAPDATAPATH = fc.getSelectedFile().getPath();
				JOptionPane.showMessageDialog(this, "路径保存成功");

			} else {
				JOptionPane.showMessageDialog(this, "没有选择文件");
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "没有选择文件");
		} finally {
			this.MapDataPath.setText(Tool.MAPDATAPATH);
			System.out.println(Tool.MAPDATAPATH);
		}

	}

	private void checkParamActionPerformed(java.awt.event.ActionEvent evt) {
		// 检查参数是否齐全
		if (checkParam()) {
			JOptionPane.showMessageDialog(this, "参数准备就绪");
		} else {
			JOptionPane.showMessageDialog(this, "参数有误！");
		}
	}

	private boolean checkParam() {
		boolean falg = false;

		if (Station.CROSS_POS == 0 || Station.GENELENGTH == 0
				|| Station.MUTA_POS == 0 || Station.POP_NUM == 0
				|| Station.SEARCH_TIME == 0) {
			falg = false;
		} else if (Tool.BUSCAP == 0 || Tool.BUSNUM_INFO == 0
				|| Tool.BUSNUM_SUPER == 0 || Tool.DATAINPUTPATH == null
				|| Tool.MAPDATAPATH == null) {
			falg = false;
		} else {
			falg = true;
		}

		return falg;
	}

	private void doGAActionPerformed(java.awt.event.ActionEvent evt) {
		// 生成优化路径

		Workbook wb = Util.getWorkbook(Tool.DATAINPUTPATH);

		for (int k = 0; k < wb.getNumberOfSheets(); k++) {

			Sheet sheet = wb.getSheet(k);

			// 确定动态参数
			Station.VARIABLE_LENGTH = sheet.getRows() - 1;

			int busNum = 3;
			if (Station.VARIABLE_LENGTH > 25) {
				busNum = Tool.BUSNUM_SUPER + 1;
			} else if (Station.VARIABLE_LENGTH > 20) {
				busNum = Tool.BUSNUM_SUPER;
			} else if (Station.VARIABLE_LENGTH > 10) {
				busNum = (Tool.BUSNUM_INFO + Tool.BUSNUM_SUPER) / 2;
			} else {
				busNum = Tool.BUSNUM_INFO;
			}
			int variable_length = Station.VARIABLE_LENGTH + busNum - 1;

			//检查动态参数
			if (variable_length != 0 && busNum != 0) {
				JOptionPane.showMessageDialog(this, "可以开始优化程序！");
				//System.out.println("可以开始优化程序！");
			} else {
				JOptionPane.showMessageDialog(this, "动态参数初始化有误，请检查程序！");
				return;
			}
			// System.out.println(variable_length);
			// System.out.println(variable_length*Station.GENELENGTH);
			//			
			InitialParameters param = new InitialParameters(variable_length,
					variable_length * Station.GENELENGTH, Station.POP_NUM,
					Station.SEARCH_TIME, Station.CROSS_POS, Station.MUTA_POS);
			DataCon dc = new DataCon(Tool.MAPDATAPATH, k, Tool.DATAINPUTPATH);
			TSPAlgorithm ta = new TSPAlgorithm();
			OverallBest ob = ta.singleGaAlgorithm(param, dc);

			obList.add(ob);

			System.out.print("(");
			for (int i = 0; i <= ob.getBestPhenotype().length - 1; i++) {
				System.out.print((int) ob.getBestPhenotype()[i] + ",");
			}
			System.out.print(")");
			System.out.println("适应值：" + ob.getBestFtn());
			System.out.println("程序运行时间：" + ob.getTime());
			// System.out.println(ob.outputTime(dc));
			System.out.println(ob.outputTime(dc));
		}

		// 序列化
		if (obList.size() == wb.getNumberOfSheets()) {
			this.serializedOb(Tool.DATAOUTPUTPATH);
			JOptionPane.showMessageDialog(this, "结果保存成功！");
		}
	}

	private void backActionPerformed(java.awt.event.ActionEvent evt) {
		// 输出时刻表
		try {
	        java.net.URI uri = java.net.URI.create("http://localhost:8080/SchoolBus/");
	        //获取当前系统桌面扩展
	        java.awt.Desktop dp = java.awt.Desktop.getDesktop();
	        //判断系统桌面是否支持要执行的功能
	        if(dp.isSupported(java.awt.Desktop.Action.BROWSE)) {
	            //获取系统默认浏览器打开链接
	            dp.browse(uri);
	        }
	    } catch(java.lang.NullPointerException e) {
	        //此为uri为空时抛出异常
	        e.printStackTrace();
	    } catch (java.io.IOException e) {
	        //此为无法获取系统默认浏览器
	        e.printStackTrace();
	    }

	}
	
	private void serializedOb(String dataOutputPath) {
		// 序列化结果
		File obfile = new File(dataOutputPath);
		ObjectOutputStream os = null;
		try {
			os = new ObjectOutputStream(new FileOutputStream(obfile));
			os.writeObject(obList);

		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				os.flush();
				os.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	private void setParamActionPerformed(java.awt.event.ActionEvent evt) {
		// 设置Ga参数
		new GAparamFrame().setVisible(true);
	}

	private void setToolActionPerformed(java.awt.event.ActionEvent evt) {
		// 设置优化参数

		new SetParam().setVisible(true);

	}

	private void inputExcelActionPerformed(java.awt.event.ActionEvent evt) {
		// 将路径中的Excel表格按格式导入参数库
		final JFileChooser fc = new JFileChooser();
		fc.showOpenDialog(this);
		try {

			// Tool.DATAINPUTPATH = file.getPath();
			if (fc.showSaveDialog(this) == 0) {
				Tool.DATAINPUTPATH = fc.getSelectedFile().getPath();
				JOptionPane.showMessageDialog(this, "路径保存成功");

			} else {
				JOptionPane.showMessageDialog(this, "没有选择文件");
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "没有选择文件");
		} finally {
			this.dataInputPath.setText(Tool.DATAINPUTPATH);
			System.out.println(Tool.DATAINPUTPATH);
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TSPframe().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField APIkey;
	private javax.swing.JButton ChooseResultPath;
	private javax.swing.JTextField MapDataPath;
	private javax.swing.JButton ReadMap;
	private javax.swing.JButton back;
	private javax.swing.JButton checkParam;
	private javax.swing.JTextField dataInputPath;
	private javax.swing.JButton doGA;
	private javax.swing.JButton inputExcel;
	private javax.swing.JButton inputFromInternet;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JSeparator jSeparator10;
	private javax.swing.JSeparator jSeparator11;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JSeparator jSeparator6;
	private javax.swing.JSeparator jSeparator7;
	private javax.swing.JSeparator jSeparator8;
	private javax.swing.JSeparator jSeparator9;
	private javax.swing.JTextField resultPathText;
	private javax.swing.JButton setParam;
	private javax.swing.JButton setTool;
	// End of variables declaration//GEN-END:variables

}