

package gadesign.TSPframes;

import gadesign.entitys.Tool;

import javax.swing.JOptionPane;

/**
 * 
 * @author Jia Ziang
 * @see ziangj92@gmail.com
 * @since 06/01/2014
 * @version 1.0
 *
 */

public class SetParam extends javax.swing.JFrame {

	/** Creates new form SetParam */
	public SetParam() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jSeparator1 = new javax.swing.JSeparator();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		busNumInfoText = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		busNumSuperText = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		capacityText = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		sepWay = new javax.swing.JComboBox();
		jLabel9 = new javax.swing.JLabel();
		singleTimeText = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		carTimeBox = new javax.swing.JCheckBox();
		studentTimeBox = new javax.swing.JCheckBox();
		jLabel12 = new javax.swing.JLabel();
		weightText1 = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		weightText2 = new javax.swing.JTextField();
		comfirmed = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		back = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u53c2\u6570\u5de5\u5177\u680f");

		jLabel2.setText("\u6821\u8f66\u6570\u91cf");

		busNumInfoText.setText("2");

		jLabel3.setText("\u8f66\u6b21");

		busNumSuperText.setText("4");

		jLabel4.setText("\u6821\u8f66\u627f\u8f7d\u91cf");

		capacityText.setText("40");

		jLabel5.setText("\u4eba\u6b21");

		jLabel8.setText("\u5212\u5206\u533a\u5757\u65b9\u5f0f");

		sepWay.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel9.setText("\u6700\u957f\u8fd0\u884c\u65f6\u95f4");

		singleTimeText.setText("120");

		jLabel10.setText("\u5206\u949f");

		jLabel11.setText("\u4f18\u5316\u6761\u4ef6");

		carTimeBox
				.setText("\u6821\u8f66\u8fd0\u884c\u603b\u65f6\u95f4\u6700\u4f18");

		studentTimeBox
				.setText("\u5b66\u751f\u65c5\u884c\u6709\u6548\u65f6\u95f4\u6700\u4f18");
		

		jLabel12.setText("\u6761\u4ef6\u6743\u91cd");

		jLabel13.setText("\uff1a");

		comfirmed.setText("\u786e\u5b9a");
		comfirmed.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comfirmedActionPerformed(evt);
			}
		});

		jButton1.setText("\u9ed8\u8ba4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		back.setText("\u8fd4\u56de");
		back.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(165, 165,
										165).addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										82, Short.MAX_VALUE).addGap(153, 153,
										153))
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(comfirmed)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel9)
																						.addContainerGap())
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel8)
																										.addContainerGap())
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jSeparator1,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																337,
																																Short.MAX_VALUE)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel2)
																																						.addComponent(
																																								jLabel11)
																																						.addComponent(
																																								jLabel4))
																																		.addGap(
																																				45,
																																				45,
																																				45)
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addGroup(
																																												layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING,
																																																false)
																																														.addGroup(
																																																layout
																																																		.createSequentialGroup()
																																																		.addComponent(
																																																				busNumInfoText,
																																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																																				67,
																																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																																		.addGap(
																																																				26,
																																																				26,
																																																				26)
																																																		.addComponent(
																																																				busNumSuperText,
																																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																																				63,
																																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																																														.addComponent(
																																																capacityText))
																																										.addGap(
																																												31,
																																												31,
																																												31)
																																										.addGroup(
																																												layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.TRAILING)
																																														.addComponent(
																																																jLabel3)
																																														.addComponent(
																																																jLabel5)))
																																						.addComponent(
																																								sepWay,
																																								0,
																																								217,
																																								Short.MAX_VALUE)
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												singleTimeText,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												156,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																												31,
																																												Short.MAX_VALUE)
																																										.addComponent(
																																												jLabel10))
																																						.addComponent(
																																								carTimeBox)
																																						.addComponent(
																																								studentTimeBox)
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel12)
																																										.addGap(
																																												18,
																																												18,
																																												18)
																																										.addComponent(
																																												weightText1,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												56,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addGap(
																																												18,
																																												18,
																																												18)
																																										.addComponent(
																																												jLabel13)
																																										.addGap(
																																												9,
																																												9,
																																												9)
																																										.addComponent(
																																												weightText2,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												41,
																																												Short.MAX_VALUE))
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								layout
																																										.createSequentialGroup()
																																										.addGap(
																																												25,
																																												25,
																																												25)
																																										.addComponent(
																																												jButton1)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																												66,
																																												Short.MAX_VALUE)
																																										.addComponent(
																																												back)))))
																										.addGap(
																												48,
																												48,
																												48)))))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGap(27, 27, 27)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												10, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																busNumSuperText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																busNumInfoText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(jLabel2))
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																capacityText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(jLabel4))
										.addGap(42, 42, 42)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																sepWay,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(41, 41, 41)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																singleTimeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10))
										.addGap(45, 45, 45)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																carTimeBox)
														.addComponent(jLabel11))
										.addGap(18, 18, 18)
										.addComponent(studentTimeBox)
										.addGap(24, 24, 24)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12)
														.addComponent(
																weightText1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																weightText2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel13))
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(comfirmed)
														.addComponent(back)
														.addComponent(jButton1))
										.addGap(63, 63, 63)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void backActionPerformed(java.awt.event.ActionEvent evt) {
		// 返回
		this.setVisible(false);

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// 恢复默认设置

	}

	private void comfirmedActionPerformed(java.awt.event.ActionEvent evt) {
		// 保存设置
		Tool.BUSCAP = Integer.parseInt(capacityText.getText());
		Tool.BUSNUM_INFO = Integer.parseInt(busNumInfoText.getText());
		Tool.BUSNUM_SUPER = Integer.parseInt(busNumSuperText.getText());
		Tool.ONEWAY_TIME = Double.parseDouble(singleTimeText.getText());
		Tool.CAR_TIME = carTimeBox.isSelected();
		Tool.STUDENT_TIME = studentTimeBox.isSelected();

		if (judgeCondition()) {
			JOptionPane.showMessageDialog(this, "参数保存成功！");
		}
	}

	private boolean judgeCondition() {
		boolean falg = false;

		if (Tool.CAR_TIME == true & Tool.STUDENT_TIME == true) {
			weightText1.setText(JOptionPane.showInputDialog("请输入条件一的权重"));
			weightText2.setText(JOptionPane.showInputDialog("请输入条件二的权重"));
			double weight1 = Double.parseDouble(weightText1.getText());
			double weight2 = Double.parseDouble(weightText2.getText());
			Tool.WEIGHT = weight1 / (weight1 + weight2);
			falg = true;
		} else if (Tool.CAR_TIME == true) {
			Tool.WEIGHT = 1;
			falg = true;
		} else if (Tool.STUDENT_TIME == true) {
			Tool.WEIGHT = 0;
			falg = true;
		} else {
			JOptionPane.showMessageDialog(this, "请选择优化条件");
		}
		return falg;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new SetParam().setVisible(true);
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton back;
	private javax.swing.JTextField busNumInfoText;
	private javax.swing.JTextField busNumSuperText;
	private javax.swing.JTextField capacityText;
	private javax.swing.JCheckBox carTimeBox;
	private javax.swing.JButton comfirmed;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JComboBox sepWay;
	private javax.swing.JTextField singleTimeText;
	private javax.swing.JCheckBox studentTimeBox;
	private javax.swing.JTextField weightText1;
	private javax.swing.JTextField weightText2;
	// End of variables declaration//GEN-END:variables

}